// _SITORRxControl_EOArchive_English.java
// Generated by EnterpriseObjects palette at Saturday, February 11, 2006 8:25:55 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _SITORRxControl_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    CrossedEllipse _nsCustomView0;
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector10, _iBHelpConnector11, _iBHelpConnector2, _iBHelpConnector3, _iBHelpConnector4, _iBHelpConnector5, _iBHelpConnector6, _iBHelpConnector7, _iBHelpConnector8, _iBHelpConnector9;
    VUMeter _vUMeter0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1, _nsMatrix2, _nsMatrix3;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField2, _eoTextField3, _eoTextField4, _eoTextField5, _eoTextField6, _eoTextField7, _eoTextField8, _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox10, _nsBox11, _nsBox12, _nsBox13, _nsBox14, _nsBox15, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsBox8, _nsBox9, _nsCustomView1, _nsSlider0, _nsSlider1;
    javax.swing.JButton _jButton0, _jButton1, _jButton10, _jButton11, _jButton12, _jButton2, _jButton3, _jButton4, _jButton5, _jButton6, _jButton7, _jButton8, _jButton9, _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView0;

    public _SITORRxControl_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsBox15 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView1");
        _nsBox14 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox21111");
        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111112");
        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111111");
        _nsBox13 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView1");
        _nsBox12 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox2111");
        _iBHelpConnector11 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton12 = (javax.swing.JButton)_registered(new javax.swing.JButton("DJ0OT"), "");
        _iBHelpConnector10 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton("FM"), "");
        _iBHelpConnector9 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("AM"), "");
        _nsMatrix3 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, -1, 8), "");
        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111121");
        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111113");
        _nsBox11 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox10 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1112");
        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111111");
        _nsBox9 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1111");
        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox11121");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111111");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox111");
        _iBHelpConnector8 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Store"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "shiftField")) != null)) {
            _nsTextField9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField9");
        } else {
            _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "memorySelectMenu")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "markFreq")) != null)) {
            _nsTextField8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField8");
        } else {
            _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "baudRateBox")) != null)) {
            _nsTextField7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField7");
        } else {
            _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        }

        _iBHelpConnector7 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton("M/S"), "");
        _iBHelpConnector6 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("MP-"), "");
        _iBHelpConnector5 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("MP+"), "");
        _iBHelpConnector4 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("SO"), "");
        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("MO"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "demodulatorModeMatrix")) != null)) {
            _nsMatrix2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix2");
        } else {
            _nsMatrix2 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 5, 8, -3), "");
        }

        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111112111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "squelchSlider")) != null)) {
            _nsSlider1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider1");
        } else {
            _nsSlider1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider2");
        }

        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lockedIndicator")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "rxPolarityButton")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Normal"), "");
        }

        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Aux"), "");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111121111");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111113111");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111211");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "inputAttenuator")) != null)) {
            _nsSlider0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider0");
        } else {
            _nsSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider211111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter")) != null)) {
            _vUMeter0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (VUMeter)replacement;
            _replacedObjects.setObjectForKey(replacement, "_vUMeter0");
        } else {
            _vUMeter0 = (VUMeter)_registered(new VUMeter(), "VUMeter");
        }

        _eoTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter.matrix")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 9, 1, 8), "");
        }

        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView11");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter.background")) != null)) {
            _nsBox2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsBox2");
        } else {
            _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "receiverName")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        }

        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "exchangeView")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tuningView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (CrossedEllipse)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (CrossedEllipse)_registered(new CrossedEllipse(), "View111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "controlView")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        _jButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("HPF"), "");
        _jButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("Soft"), "");
        _jButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Wide"), "");
        _jButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Normal"), "");
        _jButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Narrow"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bandwidthMatrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 5, 8, -3), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "auxWindow")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Aux Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "tonePairStore", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _connect(_owner(), _nsTextField9, "shiftField");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("1");
            _popup0.addItem("2");
            _popup0.addItem("3");
            _popup0.addItem("4");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "memorySelectMenu");
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _connect(_owner(), _nsTextField8, "markFreq");
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _connect(_owner(), _nsTextField7, "baudRateBox");
        }

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _connect(_owner(), _nsMatrix2, "demodulatorModeMatrix");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "auxWindow");
        }

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _connect(_owner(), _nsSlider1, "squelchSlider");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "lockedIndicator");
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "rxPolarityButton");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "auxButtonPushed", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _connect(_owner(), _nsSlider0, "inputAttenuator");
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_owner(), _vUMeter0, "vuMeter");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "receiverName");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "exchangeView");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "tuningView");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "controlView");
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "bandwidthMatrix");
        }
    }

    protected void _init() {
        super._init();
        if (!(_nsBox14.getLayout() instanceof EOViewLayout)) { _nsBox14.setLayout(new EOViewLayout()); }
        _nsBox15.setSize(1, 111);
        _nsBox15.setLocation(2, 15);
        ((EOViewLayout)_nsBox14.getLayout()).setAutosizingMask(_nsBox15, EOViewLayout.MinYMargin);
        _nsBox14.add(_nsBox15);
        _nsBox14.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField17, "Verdana", 10, Font.PLAIN);
        _nsTextField17.setEditable(false);
        _nsTextField17.setOpaque(false);
        _nsTextField17.setText("Memory");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField17.setSelectable(false);
        _nsTextField17.setEnabled(true);
        _nsTextField17.setBorder(null);
        _setFontForComponent(_nsTextField16, "Verdana", 10, Font.PLAIN);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("Mark");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);
        _setFontForComponent(_nsTextField15, "Verdana", 10, Font.PLAIN);
        _nsTextField15.setEditable(false);
        _nsTextField15.setOpaque(false);
        _nsTextField15.setText("Shift");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField15.setSelectable(false);
        _nsTextField15.setEnabled(true);
        _nsTextField15.setBorder(null);
        _setFontForComponent(_nsTextField14, "Verdana", 10, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("Baud");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField14.setSelectable(false);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);
        if (!(_nsBox12.getLayout() instanceof EOViewLayout)) { _nsBox12.setLayout(new EOViewLayout()); }
        _nsBox13.setSize(1, 111);
        _nsBox13.setLocation(2, 15);
        ((EOViewLayout)_nsBox12.getLayout()).setAutosizingMask(_nsBox13, EOViewLayout.MinYMargin);
        _nsBox12.add(_nsBox13);
        _nsBox12.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_jButton12, "Lucida Grande", 11, Font.PLAIN);
        _jButton12.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton11, "Lucida Grande", 11, Font.PLAIN);
        _jButton11.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton10, "Lucida Grande", 11, Font.PLAIN);
        _jButton10.setMargin(new Insets(0, 2, 0, 2));
        _jButton10.setSize(58, 21);
        _jButton10.setLocation(0, 0);
        _nsMatrix3.add(_jButton10);
        _jButton11.setSize(58, 21);
        _jButton11.setLocation(0, 29);
        _nsMatrix3.add(_jButton11);
        _jButton12.setSize(58, 21);
        _jButton12.setLocation(0, 58);
        _nsMatrix3.add(_jButton12);
        _setFontForComponent(_nsTextField13, "Verdana", 10, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("Demodulator");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);
        _setFontForComponent(_nsTextField12, "Verdana", 10, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("Filters");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField12.setSelectable(false);
        _nsTextField12.setEnabled(true);
        _nsTextField12.setBorder(null);
        if (!(_nsBox10.getLayout() instanceof EOViewLayout)) { _nsBox10.setLayout(new EOViewLayout()); }
        _nsBox11.setSize(125, 1);
        _nsBox11.setLocation(2, 2);
        ((EOViewLayout)_nsBox10.getLayout()).setAutosizingMask(_nsBox11, EOViewLayout.MinYMargin);
        _nsBox10.add(_nsBox11);
        _nsBox10.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField11, "Verdana", 10, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("Mode");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField11.setSelectable(false);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        if (!(_nsBox8.getLayout() instanceof EOViewLayout)) { _nsBox8.setLayout(new EOViewLayout()); }
        _nsBox9.setSize(125, 1);
        _nsBox9.setLocation(2, 2);
        ((EOViewLayout)_nsBox8.getLayout()).setAutosizingMask(_nsBox9, EOViewLayout.MinYMargin);
        _nsBox8.add(_nsBox9);
        _nsBox8.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(125, 1);
        _nsBox7.setLocation(2, 2);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField10, "Verdana", 10, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(125, 1);
        _nsBox5.setLocation(2, 2);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsButton2, "Lucida Grande", 11, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _setFontForComponent(_nsTextField9, "Verdana", 10, Font.PLAIN);
            _nsTextField9.setEditable(true);
            _nsTextField9.setOpaque(true);
            _nsTextField9.setText("170");
            _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField9.setSelectable(true);
            _nsTextField9.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 9, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _setFontForComponent(_nsTextField8, "Verdana", 10, Font.PLAIN);
            _nsTextField8.setEditable(true);
            _nsTextField8.setOpaque(true);
            _nsTextField8.setText("2125");
            _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField8.setSelectable(true);
            _nsTextField8.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _setFontForComponent(_nsTextField7, "Verdana", 10, Font.PLAIN);
            _nsTextField7.setEditable(true);
            _nsTextField7.setOpaque(true);
            _nsTextField7.setText("45.45");
            _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField7.setSelectable(true);
            _nsTextField7.setEnabled(true);
        }

        _setFontForComponent(_jButton9, "Lucida Grande", 11, Font.PLAIN);
        _jButton9.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton8, "Lucida Grande", 11, Font.PLAIN);
        _jButton8.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton7, "Lucida Grande", 11, Font.PLAIN);
        _jButton7.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton6, "Lucida Grande", 11, Font.PLAIN);
        _jButton6.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton5, "Lucida Grande", 11, Font.PLAIN);
        _jButton5.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _jButton5.setSize(45, 20);
            _jButton5.setLocation(0, 0);
            _nsMatrix2.add(_jButton5);
            _jButton6.setSize(45, 20);
            _jButton6.setLocation(53, 0);
            _nsMatrix2.add(_jButton6);
            _jButton7.setSize(45, 20);
            _jButton7.setLocation(106, 0);
            _nsMatrix2.add(_jButton7);
            _jButton8.setSize(45, 20);
            _jButton8.setLocation(159, 0);
            _nsMatrix2.add(_jButton8);
            _jButton9.setSize(45, 20);
            _jButton9.setLocation(212, 0);
            _nsMatrix2.add(_jButton9);
        }

        _setFontForComponent(_nsTextField6, "Verdana", 10, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Squelch");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _setFontForComponent(_nsSlider1, "Helvetica", 12, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField5, "Verdana", 10, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Locked:");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField4.setEditable(false);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(false);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField3, "Verdana", 9, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("-24");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Verdana", 9, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("-12");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Verdana", 9, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("0dB");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _setFontForComponent(_nsSlider0, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_vUMeter0, _nsBox2, "background");
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_vUMeter0, _nsMatrix1, "matrix");
        }

        _setFontForComponent(_eoTextField8, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField7, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField6, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField5, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField4, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Lucida Grande", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _eoTextField0.setSize(6, 15);
            _eoTextField0.setLocation(0, 0);
            _nsMatrix1.add(_eoTextField0);
            _eoTextField1.setSize(6, 15);
            _eoTextField1.setLocation(7, 0);
            _nsMatrix1.add(_eoTextField1);
            _eoTextField2.setSize(6, 15);
            _eoTextField2.setLocation(14, 0);
            _nsMatrix1.add(_eoTextField2);
            _eoTextField3.setSize(6, 15);
            _eoTextField3.setLocation(21, 0);
            _nsMatrix1.add(_eoTextField3);
            _eoTextField4.setSize(6, 15);
            _eoTextField4.setLocation(28, 0);
            _nsMatrix1.add(_eoTextField4);
            _eoTextField5.setSize(6, 15);
            _eoTextField5.setLocation(35, 0);
            _nsMatrix1.add(_eoTextField5);
            _eoTextField6.setSize(6, 15);
            _eoTextField6.setLocation(42, 0);
            _nsMatrix1.add(_eoTextField6);
            _eoTextField7.setSize(6, 15);
            _eoTextField7.setLocation(49, 0);
            _nsMatrix1.add(_eoTextField7);
            _eoTextField8.setSize(6, 15);
            _eoTextField8.setLocation(56, 0);
            _nsMatrix1.add(_eoTextField8);
        }

        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsMatrix1.setSize(63, 15);
        _nsMatrix1.setLocation(1, 1);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsMatrix1);

        if (_replacedObjects.objectForKey("_nsBox2") == null) {
            if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
            _nsBox3.setSize(64, 17);
            _nsBox3.setLocation(1, 1);
            ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
            _nsBox2.add(_nsBox3);
            _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Verdana", 10, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(false);
            _nsTextField0.setText("Main Receiver");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField0.setSelectable(false);
            _nsTextField0.setEnabled(true);
            _nsTextField0.setBorder(null);
        }

        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(80, 15);
        _nsTextField0.setLocation(31, 16);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField0);
        _nsBox2.setSize(66, 19);
        _nsBox2.setLocation(40, 122);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox2);
        _nsSlider0.setSize(80, 16);
        _nsSlider0.setLocation(34, 161);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsSlider0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsSlider0);
        _nsTextField1.setSize(29, 14);
        _nsTextField1.setLocation(94, 144);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsTextField2.setSize(30, 14);
        _nsTextField2.setLocation(59, 144);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField2);
        _nsTextField3.setSize(30, 14);
        _nsTextField3.setLocation(25, 144);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField3);
        _nsButton0.setSize(39, 18);
        _nsButton0.setLocation(20, 79);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton0);
        _nsButton1.setSize(55, 18);
        _nsButton1.setLocation(67, 79);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton1);
        _nsTextField4.setSize(15, 15);
        _nsTextField4.setLocation(84, 44);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField4);
        _nsTextField5.setSize(54, 15);
        _nsTextField5.setLocation(27, 44);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField5);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(140, 195);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(false);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
            _nsCustomView0.setSize(140, 140);
            _nsCustomView0.setLocation(0, 34);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsCustomView0);
            _nsTextView0.setSize(630, 196);
            _nsTextView0.setLocation(141, 34);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextView0);
            _nsBox0.setSize(144, 199);
            _nsBox0.setLocation(769, 32);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsBox0);
            _nsSlider1.setSize(58, 16);
            _nsSlider1.setLocation(38, 202);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsSlider1, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsSlider1);
            _nsTextField6.setSize(47, 15);
            _nsTextField6.setLocation(43, 182);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField6);
        }

        _setFontForComponent(_jButton4, "Lucida Grande", 11, Font.PLAIN);
        _jButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton3, "Lucida Grande", 11, Font.PLAIN);
        _jButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton2, "Lucida Grande", 11, Font.PLAIN);
        _jButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton1, "Lucida Grande", 11, Font.PLAIN);
        _jButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton0, "Lucida Grande", 11, Font.PLAIN);
        _jButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jButton0.setSize(45, 20);
            _jButton0.setLocation(0, 0);
            _nsMatrix0.add(_jButton0);
            _jButton1.setSize(45, 20);
            _jButton1.setLocation(53, 0);
            _nsMatrix0.add(_jButton1);
            _jButton2.setSize(45, 20);
            _jButton2.setLocation(106, 0);
            _nsMatrix0.add(_jButton2);
            _jButton3.setSize(45, 20);
            _jButton3.setLocation(159, 0);
            _nsMatrix0.add(_jButton3);
            _jButton4.setSize(45, 20);
            _jButton4.setLocation(212, 0);
            _nsMatrix0.add(_jButton4);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(257, 20);
        _nsMatrix0.setLocation(300, 95);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsBox4.setSize(96, 5);
        _nsBox4.setLocation(309, 18);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox4);
        _nsTextField10.setSize(37, 15);
        _nsTextField10.setLocation(289, 99);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField10);
        _nsBox6.setSize(94, 5);
        _nsBox6.setLocation(451, 77);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox6);
        _nsBox8.setSize(96, 5);
        _nsBox8.setLocation(449, 18);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox8, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox8);
        _nsTextField11.setSize(37, 15);
        _nsTextField11.setLocation(414, 12);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField11);
        _nsBox10.setSize(94, 5);
        _nsBox10.setLocation(309, 77);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox10, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox10);
        _nsMatrix2.setSize(257, 20);
        _nsMatrix2.setLocation(300, 32);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix2);
        _nsTextField12.setSize(37, 15);
        _nsTextField12.setLocation(411, 72);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField12);
        _nsTextField13.setSize(72, 15);
        _nsTextField13.setLocation(194, 13);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField13);
        _nsMatrix3.setSize(58, 76);
        _nsMatrix3.setLocation(203, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix3);
        _nsBox12.setSize(5, 128);
        _nsBox12.setLocation(283, 5);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox12, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox12);
        _nsTextField9.setSize(46, 21);
        _nsTextField9.setLocation(67, 39);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField9);
        _nsTextField14.setSize(37, 15);
        _nsTextField14.setLocation(133, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField14);
        _nsTextField15.setSize(44, 15);
        _nsTextField15.setLocation(73, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField15);
        _nsTextField16.setSize(45, 15);
        _nsTextField16.setLocation(21, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField16);
        _nsTextField8.setSize(46, 21);
        _nsTextField8.setLocation(11, 39);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField8);
        _nsTextField17.setSize(48, 15);
        _nsTextField17.setLocation(10, 79);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField17);
        _popup0.setSize(41, 15);
        _popup0.setLocation(67, 80);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsButton2.setSize(41, 20);
        _nsButton2.setLocation(122, 78);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton2);
        _nsBox14.setSize(5, 128);
        _nsBox14.setLocation(177, 5);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox14, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox14);
        _nsTextField7.setSize(46, 21);
        _nsTextField7.setLocation(124, 39);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField7);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(570, 145);
            _eoFrame0.setTitle("Main Receiver");
            _eoFrame0.setLocation(-1059, 337);
            _eoFrame0.setSize(570, 145);
        }
    }
}
