// _SynchAM_EOArchive_English.java
// Generated by EnterpriseObjects palette at Saturday, May 19, 2007 10:25:10 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _SynchAM_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    AMConfig _aMConfig0;
    AMWaterfall _nsCustomView0;
    Oscilloscope _nsCustomView1;
    VUMeter _vUMeter0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1, _nsMatrix2, _nsMatrix3, _nsMatrix4;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField10, _eoTextField11, _eoTextField12, _eoTextField13, _eoTextField14, _eoTextField15, _eoTextField16, _eoTextField17, _eoTextField18, _eoTextField19, _eoTextField2, _eoTextField20, _eoTextField21, _eoTextField22, _eoTextField23, _eoTextField24, _eoTextField25, _eoTextField26, _eoTextField27, _eoTextField28, _eoTextField29, _eoTextField3, _eoTextField30, _eoTextField31, _eoTextField32, _eoTextField33, _eoTextField34, _eoTextField35, _eoTextField36, _eoTextField37, _eoTextField38, _eoTextField39, _eoTextField4, _eoTextField40, _eoTextField41, _eoTextField42, _eoTextField43, _eoTextField44, _eoTextField45, _eoTextField46, _eoTextField47, _eoTextField48, _eoTextField49, _eoTextField5, _eoTextField50, _eoTextField51, _eoTextField52, _eoTextField53, _eoTextField54, _eoTextField55, _eoTextField56, _eoTextField57, _eoTextField6, _eoTextField7, _eoTextField8, _eoTextField9, _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField18, _nsTextField19, _nsTextField2, _nsTextField20, _nsTextField21, _nsTextField22, _nsTextField23, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox10, _nsBox11, _nsBox12, _nsBox13, _nsBox14, _nsBox15, _nsBox16, _nsBox17, _nsBox18, _nsBox19, _nsBox2, _nsBox20, _nsBox21, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsBox8, _nsBox9, _nsColorWell0, _nsCustomView2, _nsCustomView3, _nsCustomView4, _nsCustomView5, _nsCustomView6, _nsSlider0, _nsSlider1, _nsSlider2, _nsSlider3, _nsSlider4, _nsSlider5, _nsSlider6, _nsSlider7, _nsSlider8, _nsView0, _nsView1;
    javax.swing.JButton _jButton0, _jButton1, _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JCheckBox _nsButton3, _nsButton4, _nsButton5;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView2;
    javax.swing.JTabbedPane _nsTabView0;

    public _SynchAM_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _nsBox21 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox20 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox111");
        _nsBox19 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox18 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111111");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsBox17 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView1");
        _nsBox16 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1211");
        _nsBox15 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox14 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111121");
        _nsBox13 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox12 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.auralAttenuator")) != null)) {
            _nsCustomView6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView6");
        } else {
            _nsCustomView6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View21");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.auralControl")) != null)) {
            _nsCustomView5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView5");
        } else {
            _nsCustomView5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.auralActiveButton")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Inactive"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.fileSpeedCheckbox")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Fast Sound file playback."), "NSButton4");
        }

        _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton11");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Baseline"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.oscilloscope")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (Oscilloscope)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (Oscilloscope)_registered(new Oscilloscope(), "View12");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "equalizerCheckbox")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Parametric Equalizer"), "NSButton41");
        }

        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eq4800Slider")) != null)) {
            _nsSlider8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider8");
        } else {
            _nsSlider8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider2111111");
        }

        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eq2400Slider")) != null)) {
            _nsSlider7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider7");
        } else {
            _nsSlider7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider211111");
        }

        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eq1200Slider")) != null)) {
            _nsSlider6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider6");
        } else {
            _nsSlider6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider21111");
        }

        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eq600Slider")) != null)) {
            _nsSlider5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider5");
        } else {
            _nsSlider5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider2111");
        }

        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eq300Slider")) != null)) {
            _nsSlider4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider4");
        } else {
            _nsSlider4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "muteCheckbox")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Mute"), "NSButton4");
        }

        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111121");
        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111112");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "volumeSlider")) != null)) {
            _nsSlider3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider3");
        } else {
            _nsSlider3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider21");
        }

        _nsBox11 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox10 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox11");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lockOffsetSlider")) != null)) {
            _nsSlider2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider2");
        } else {
            _nsSlider2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider21");
        }

        _nsBox9 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lockRangeSlider")) != null)) {
            _nsSlider1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider1");
        } else {
            _nsSlider1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider2");
        }

        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lockLight")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _eoTextField57 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField56 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField55 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField54 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField53 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField52 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField51 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField50 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField49 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField48 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField47 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField46 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField45 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField44 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField43 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField42 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField41 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField40 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField39 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField38 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField37 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "waterfall.waterfallLabel")) != null)) {
            _nsMatrix4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix4");
        } else {
            _nsMatrix4 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 21, -2, 8), "");
        }

        _eoTextField36 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField35 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField34 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField33 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField32 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField31 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField30 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField29 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField28 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField27 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField26 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField25 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField24 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "waterfall.waterfallTicks")) != null)) {
            _nsMatrix3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix3");
        } else {
            _nsMatrix3 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 23, 29, 8), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "waterfall")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AMWaterfall)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (AMWaterfall)_registered(new AMWaterfall(), "View");
        }

        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111112");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter")) != null)) {
            _vUMeter0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (VUMeter)replacement;
            _replacedObjects.setObjectForKey(replacement, "_vUMeter0");
        } else {
            _vUMeter0 = (VUMeter)_registered(new VUMeter(), "VUMeter");
        }

        _eoTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter.matrix")) != null)) {
            _nsMatrix2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix2");
        } else {
            _nsMatrix2 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 9, 1, 8), "");
        }

        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter.background")) != null)) {
            _nsBox2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsBox2");
        } else {
            _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        }

        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "inputAttenuator")) != null)) {
            _nsSlider0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider0");
        } else {
            _nsSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider21");
        }

        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView4");
        } else {
            _nsCustomView4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        _jButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Waveform"), "");
        _jButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Spectrum"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.waveformMatrix")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, -1, 16), "");
        }

        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.specLabel")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 5, 55, 8), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.plotColor")) != null)) {
            _nsColorWell0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell0");
        } else {
            _nsColorWell0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "22");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.inputPad")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.soundInputControls")) != null)) {
            _nsCustomView3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView3");
        } else {
            _nsCustomView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.activeButton")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Inactive"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config")) != null)) {
            _aMConfig0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AMConfig)replacement;
            _replacedObjects.setObjectForKey(replacement, "_aMConfig0");
        } else {
            _aMConfig0 = (AMConfig)_registered(new AMConfig(), "AMConfig");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.soundFileControls")) != null)) {
            _nsCustomView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView2");
        } else {
            _nsCustomView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View2");
        }

        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Config Panel");
        }

        _nsView2 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _popup0.setModel(new javax.swing.DefaultComboBoxModel());
        _popup0.addItem("Avg.");
        _popup0.addItem("0.2 s");
        _popup0.addItem("0.5 s");
        _popup0.addItem("1.5 s");
        _popup0.addItem("4.0 s");

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_owner(), _aMConfig0, "config");
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "equalizerCheckbox");
        }

        if (_replacedObjects.objectForKey("_nsSlider8") == null) {
            _connect(_owner(), _nsSlider8, "eq4800Slider");
        }

        if (_replacedObjects.objectForKey("_nsSlider7") == null) {
            _connect(_owner(), _nsSlider7, "eq2400Slider");
        }

        if (_replacedObjects.objectForKey("_nsSlider6") == null) {
            _connect(_owner(), _nsSlider6, "eq1200Slider");
        }

        if (_replacedObjects.objectForKey("_nsSlider5") == null) {
            _connect(_owner(), _nsSlider5, "eq600Slider");
        }

        if (_replacedObjects.objectForKey("_nsSlider4") == null) {
            _connect(_owner(), _nsSlider4, "eq300Slider");
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "muteCheckbox");
        }

        if (_replacedObjects.objectForKey("_nsSlider3") == null) {
            _connect(_owner(), _nsSlider3, "volumeSlider");
        }

        if (_replacedObjects.objectForKey("_nsSlider2") == null) {
            _connect(_owner(), _nsSlider2, "lockOffsetSlider");
        }

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _connect(_owner(), _nsSlider1, "lockRangeSlider");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "lockLight");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "waterfall");
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_owner(), _vUMeter0, "vuMeter");
        }

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _connect(_owner(), _nsSlider0, "inputAttenuator");
        }

        if (_replacedObjects.objectForKey("_nsCustomView4") == null) {
            _connect(_owner(), _nsCustomView4, "view");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _owner(), "modemObj");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField23, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField23.setEditable(false);
        _nsTextField23.setOpaque(false);
        _nsTextField23.setText("State:");
        _nsTextField23.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField23.setSelectable(false);
        _nsTextField23.setEnabled(true);
        _nsTextField23.setBorder(null);
        if (!(_nsBox20.getLayout() instanceof EOViewLayout)) { _nsBox20.setLayout(new EOViewLayout()); }
        _nsBox21.setSize(125, 1);
        _nsBox21.setLocation(2, 2);
        ((EOViewLayout)_nsBox20.getLayout()).setAutosizingMask(_nsBox21, EOViewLayout.MinYMargin);
        _nsBox20.add(_nsBox21);
        _nsBox20.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsBox18.getLayout() instanceof EOViewLayout)) { _nsBox18.setLayout(new EOViewLayout()); }
        _nsBox19.setSize(125, 1);
        _nsBox19.setLocation(2, 2);
        ((EOViewLayout)_nsBox18.getLayout()).setAutosizingMask(_nsBox19, EOViewLayout.MinYMargin);
        _nsBox18.add(_nsBox19);
        _nsBox18.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField22, "Verdana", 10, Font.PLAIN);
        _nsTextField22.setEditable(false);
        _nsTextField22.setOpaque(false);
        _nsTextField22.setText("Output Level:");
        _nsTextField22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField22.setSelectable(false);
        _nsTextField22.setEnabled(true);
        _nsTextField22.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsCustomView5.setSize(523, 22);
        _nsCustomView5.setLocation(41, 81);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView5, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView5);
        _nsCustomView6.setSize(436, 30);
        _nsCustomView6.setLocation(128, 115);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView6, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView6);
        _nsTextField22.setSize(76, 15);
        _nsTextField22.setLocation(49, 122);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField22, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField22);
        _nsBox18.setSize(555, 5);
        _nsBox18.setLocation(41, 173);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox18, EOViewLayout.MinYMargin);
        _nsView1.add(_nsBox18);
        _nsBox20.setSize(555, 5);
        _nsBox20.setLocation(41, 52);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox20, EOViewLayout.MinYMargin);
        _nsView1.add(_nsBox20);
        _nsTextField23.setSize(39, 13);
        _nsTextField23.setLocation(43, 19);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField23, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField23);
        _nsButton2.setSize(58, 21);
        _nsButton2.setLocation(79, 15);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton2);
        _setFontForComponent(_nsTextField21, "Verdana", 10, Font.PLAIN);
        _nsTextField21.setEditable(false);
        _nsTextField21.setOpaque(false);
        _nsTextField21.setText("Pad");
        _nsTextField21.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField21.setSelectable(false);
        _nsTextField21.setEnabled(true);
        _nsTextField21.setBorder(null);
        _setFontForComponent(_nsTextField20, "Verdana", 10, Font.PLAIN);
        _nsTextField20.setEditable(false);
        _nsTextField20.setOpaque(false);
        _nsTextField20.setText("dB");
        _nsTextField20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField20.setSelectable(false);
        _nsTextField20.setEnabled(true);
        _nsTextField20.setBorder(null);
        if (!(_nsBox16.getLayout() instanceof EOViewLayout)) { _nsBox16.setLayout(new EOViewLayout()); }
        _nsBox17.setSize(125, 1);
        _nsBox17.setLocation(2, 2);
        ((EOViewLayout)_nsBox16.getLayout()).setAutosizingMask(_nsBox17, EOViewLayout.MinYMargin);
        _nsBox16.add(_nsBox17);
        _nsBox16.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsBox15.getLayout() instanceof EOViewLayout)) { _nsBox15.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(406, 15);
        _nsMatrix0.setLocation(83, -1);
        ((EOViewLayout)_nsBox15.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsBox15.add(_nsMatrix0);
        if (!(_nsBox14.getLayout() instanceof EOViewLayout)) { _nsBox14.setLayout(new EOViewLayout()); }
        _nsBox15.setSize(518, 14);
        _nsBox15.setLocation(1, 1);
        ((EOViewLayout)_nsBox14.getLayout()).setAutosizingMask(_nsBox15, EOViewLayout.MinYMargin);
        _nsBox14.add(_nsBox15);
        _nsBox14.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField19, "Verdana", 10, Font.PLAIN);
        _nsTextField19.setEditable(false);
        _nsTextField19.setOpaque(false);
        _nsTextField19.setText("Plots");
        _nsTextField19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField19.setSelectable(false);
        _nsTextField19.setEnabled(true);
        _nsTextField19.setBorder(null);
        if (!(_nsBox13.getLayout() instanceof EOViewLayout)) { _nsBox13.setLayout(new EOViewLayout()); }
        _nsButton5.setSize(169, 17);
        _nsButton5.setLocation(18, 351);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsBox13.add(_nsButton5);
        _nsColorWell0.setSize(54, 26);
        _nsColorWell0.setLocation(91, 293);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsColorWell0, EOViewLayout.MinYMargin);
        _nsBox13.add(_nsColorWell0);
        _nsTextField19.setSize(72, 15);
        _nsTextField19.setLocation(23, 298);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsTextField19, EOViewLayout.MinYMargin);
        _nsBox13.add(_nsTextField19);
        if (!(_nsBox12.getLayout() instanceof EOViewLayout)) { _nsBox12.setLayout(new EOViewLayout()); }
        _nsBox13.setSize(172, 392);
        _nsBox13.setLocation(2, 2);
        ((EOViewLayout)_nsBox12.getLayout()).setAutosizingMask(_nsBox13, EOViewLayout.MinYMargin);
        _nsBox12.add(_nsBox13);
        _nsBox12.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField18, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField18.setEditable(false);
        _nsTextField18.setOpaque(false);
        _nsTextField18.setText("State:");
        _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField18.setSelectable(false);
        _nsTextField18.setEnabled(true);
        _nsTextField18.setBorder(null);

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsCustomView6, "auralAttenuator");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsCustomView5, "auralControl");
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 11, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsButton2, "auralActiveButton");
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 10, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsButton5, "fileSpeedCheckbox");
        }

        _setFontForComponent(_popup0, "Lucida Grande", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_nsCustomView1, _popup0, "averagePopupMenu");
        }

        _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_nsCustomView1, _nsButton1, "baselineButton");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsCustomView1, "oscilloscope");
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Verdana", 10, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField17, "Verdana", 10, Font.PLAIN);
        _nsTextField17.setEditable(false);
        _nsTextField17.setOpaque(false);
        _nsTextField17.setText("3200 Hz");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField17.setSelectable(false);
        _nsTextField17.setEnabled(true);
        _nsTextField17.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider8") == null) {
            _setFontForComponent(_nsSlider8, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        _setFontForComponent(_nsTextField16, "Verdana", 10, Font.PLAIN);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("1600 Hz");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider7") == null) {
            _setFontForComponent(_nsSlider7, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        _setFontForComponent(_nsTextField15, "Verdana", 10, Font.PLAIN);
        _nsTextField15.setEditable(false);
        _nsTextField15.setOpaque(false);
        _nsTextField15.setText("800 Hz");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField15.setSelectable(false);
        _nsTextField15.setEnabled(true);
        _nsTextField15.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider6") == null) {
            _setFontForComponent(_nsSlider6, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        _setFontForComponent(_nsTextField14, "Verdana", 10, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("400 Hz");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField14.setSelectable(false);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider5") == null) {
            _setFontForComponent(_nsSlider5, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        _setFontForComponent(_nsTextField13, "Verdana", 10, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("200 Hz");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider4") == null) {
            _setFontForComponent(_nsSlider4, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Verdana", 10, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField12, "Verdana", 9, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("-25");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField12.setSelectable(false);
        _nsTextField12.setEnabled(true);
        _nsTextField12.setBorder(null);
        _setFontForComponent(_nsTextField11, "Verdana", 9, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("0dB");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField11.setSelectable(false);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        _setFontForComponent(_nsTextField10, "Verdana", 9, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("-50");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        _setFontForComponent(_nsTextField9, "Verdana", 10, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Volume");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider3") == null) {
            _setFontForComponent(_nsSlider3, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        if (!(_nsBox10.getLayout() instanceof EOViewLayout)) { _nsBox10.setLayout(new EOViewLayout()); }
        _nsBox11.setSize(125, 1);
        _nsBox11.setLocation(2, 2);
        ((EOViewLayout)_nsBox10.getLayout()).setAutosizingMask(_nsBox11, EOViewLayout.MinYMargin);
        _nsBox10.add(_nsBox11);
        _nsBox10.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField8, "Verdana", 10, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Carrier");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Verdana", 10, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Offset");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider2") == null) {
            _setFontForComponent(_nsSlider2, "Helvetica", 12, Font.PLAIN);
        }

        if (!(_nsBox8.getLayout() instanceof EOViewLayout)) { _nsBox8.setLayout(new EOViewLayout()); }
        _nsBox9.setSize(125, 1);
        _nsBox9.setLocation(2, 2);
        ((EOViewLayout)_nsBox8.getLayout()).setAutosizingMask(_nsBox9, EOViewLayout.MinYMargin);
        _nsBox8.add(_nsBox9);
        _nsBox8.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField6, "Verdana", 10, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Range");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _setFontForComponent(_nsSlider1, "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        _setFontForComponent(_nsTextField5, "Verdana", 10, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Locked");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField4.setEditable(false);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(false);
            _nsTextField4.setEnabled(true);
        }

        if (!(_nsBox7.getLayout() instanceof EOViewLayout)) { _nsBox7.setLayout(new EOViewLayout()); }
        _nsTextField4.setSize(13, 13);
        _nsTextField4.setLocation(67, 14);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsTextField4);
        _nsTextField5.setSize(55, 15);
        _nsTextField5.setLocation(8, 12);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsTextField5);
        _nsSlider1.setSize(91, 12);
        _nsSlider1.setLocation(66, 94);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsSlider1, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsSlider1);
        _nsTextField6.setSize(55, 15);
        _nsTextField6.setLocation(0, 92);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsTextField6);
        _nsBox8.setSize(136, 5);
        _nsBox8.setLocation(21, 41);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsBox8, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsBox8);
        _nsSlider2.setSize(91, 12);
        _nsSlider2.setLocation(66, 65);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsSlider2, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsSlider2);
        _nsTextField7.setSize(55, 15);
        _nsTextField7.setLocation(0, 63);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsTextField7);
        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(173, 133);
        _nsBox7.setLocation(2, 2);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsMatrix4.setSize(783, 11);
        _nsMatrix4.setLocation(-13, 2);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsMatrix4, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsMatrix4);
        _nsMatrix3.setSize(827, 13);
        _nsMatrix3.setLocation(1, -8);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsMatrix3, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsMatrix3);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(776, 13);
        _nsBox5.setLocation(1, 1);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_eoTextField57, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField56, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField55, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField54, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField53, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField52, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField51, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField50, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField49, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField48, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField47, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField46, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField45, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField44, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField43, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField42, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField41, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField40, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField39, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField38, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField37, "Lucida Grande", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix4") == null) {
            _eoTextField37.setSize(40, 11);
            _eoTextField37.setLocation(0, 0);
            _nsMatrix4.add(_eoTextField37);
            _eoTextField38.setSize(40, 11);
            _eoTextField38.setLocation(37, 0);
            _nsMatrix4.add(_eoTextField38);
            _eoTextField39.setSize(40, 11);
            _eoTextField39.setLocation(74, 0);
            _nsMatrix4.add(_eoTextField39);
            _eoTextField40.setSize(40, 11);
            _eoTextField40.setLocation(111, 0);
            _nsMatrix4.add(_eoTextField40);
            _eoTextField41.setSize(40, 11);
            _eoTextField41.setLocation(148, 0);
            _nsMatrix4.add(_eoTextField41);
            _eoTextField42.setSize(40, 11);
            _eoTextField42.setLocation(185, 0);
            _nsMatrix4.add(_eoTextField42);
            _eoTextField43.setSize(40, 11);
            _eoTextField43.setLocation(222, 0);
            _nsMatrix4.add(_eoTextField43);
            _eoTextField44.setSize(40, 11);
            _eoTextField44.setLocation(259, 0);
            _nsMatrix4.add(_eoTextField44);
            _eoTextField45.setSize(40, 11);
            _eoTextField45.setLocation(296, 0);
            _nsMatrix4.add(_eoTextField45);
            _eoTextField46.setSize(40, 11);
            _eoTextField46.setLocation(333, 0);
            _nsMatrix4.add(_eoTextField46);
            _eoTextField47.setSize(40, 11);
            _eoTextField47.setLocation(371, 0);
            _nsMatrix4.add(_eoTextField47);
            _eoTextField48.setSize(40, 11);
            _eoTextField48.setLocation(408, 0);
            _nsMatrix4.add(_eoTextField48);
            _eoTextField49.setSize(40, 11);
            _eoTextField49.setLocation(445, 0);
            _nsMatrix4.add(_eoTextField49);
            _eoTextField50.setSize(40, 11);
            _eoTextField50.setLocation(482, 0);
            _nsMatrix4.add(_eoTextField50);
            _eoTextField51.setSize(40, 11);
            _eoTextField51.setLocation(519, 0);
            _nsMatrix4.add(_eoTextField51);
            _eoTextField52.setSize(40, 11);
            _eoTextField52.setLocation(556, 0);
            _nsMatrix4.add(_eoTextField52);
            _eoTextField53.setSize(40, 11);
            _eoTextField53.setLocation(593, 0);
            _nsMatrix4.add(_eoTextField53);
            _eoTextField54.setSize(40, 11);
            _eoTextField54.setLocation(630, 0);
            _nsMatrix4.add(_eoTextField54);
            _eoTextField55.setSize(40, 11);
            _eoTextField55.setLocation(667, 0);
            _nsMatrix4.add(_eoTextField55);
            _eoTextField56.setSize(40, 11);
            _eoTextField56.setLocation(704, 0);
            _nsMatrix4.add(_eoTextField56);
            _eoTextField57.setSize(40, 11);
            _eoTextField57.setLocation(742, 0);
            _nsMatrix4.add(_eoTextField57);
            _setFontForComponent(_nsMatrix4, "Lucida Grande", 9, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_nsCustomView0, _nsMatrix4, "waterfallLabel");
        }

        _setFontForComponent(_eoTextField36, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField35, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField34, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField33, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField32, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField31, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField30, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField29, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField28, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField27, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField26, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField25, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField24, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField23, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField22, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField21, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField20, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField19, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField18, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField17, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField16, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField15, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);
        _setFontForComponent(_eoTextField14, "Lucida Grande", 10, Font.PLAIN + Font.BOLD);

        if (_replacedObjects.objectForKey("_nsMatrix3") == null) {
            _eoTextField14.setSize(8, 13);
            _eoTextField14.setLocation(0, 0);
            _nsMatrix3.add(_eoTextField14);
            _eoTextField15.setSize(8, 13);
            _eoTextField15.setLocation(37, 0);
            _nsMatrix3.add(_eoTextField15);
            _eoTextField16.setSize(8, 13);
            _eoTextField16.setLocation(74, 0);
            _nsMatrix3.add(_eoTextField16);
            _eoTextField17.setSize(8, 13);
            _eoTextField17.setLocation(111, 0);
            _nsMatrix3.add(_eoTextField17);
            _eoTextField18.setSize(8, 13);
            _eoTextField18.setLocation(148, 0);
            _nsMatrix3.add(_eoTextField18);
            _eoTextField19.setSize(8, 13);
            _eoTextField19.setLocation(185, 0);
            _nsMatrix3.add(_eoTextField19);
            _eoTextField20.setSize(8, 13);
            _eoTextField20.setLocation(222, 0);
            _nsMatrix3.add(_eoTextField20);
            _eoTextField21.setSize(8, 13);
            _eoTextField21.setLocation(260, 0);
            _nsMatrix3.add(_eoTextField21);
            _eoTextField22.setSize(8, 13);
            _eoTextField22.setLocation(297, 0);
            _nsMatrix3.add(_eoTextField22);
            _eoTextField23.setSize(8, 13);
            _eoTextField23.setLocation(334, 0);
            _nsMatrix3.add(_eoTextField23);
            _eoTextField24.setSize(8, 13);
            _eoTextField24.setLocation(371, 0);
            _nsMatrix3.add(_eoTextField24);
            _eoTextField25.setSize(8, 13);
            _eoTextField25.setLocation(408, 0);
            _nsMatrix3.add(_eoTextField25);
            _eoTextField26.setSize(8, 13);
            _eoTextField26.setLocation(445, 0);
            _nsMatrix3.add(_eoTextField26);
            _eoTextField27.setSize(8, 13);
            _eoTextField27.setLocation(482, 0);
            _nsMatrix3.add(_eoTextField27);
            _eoTextField28.setSize(8, 13);
            _eoTextField28.setLocation(520, 0);
            _nsMatrix3.add(_eoTextField28);
            _eoTextField29.setSize(8, 13);
            _eoTextField29.setLocation(557, 0);
            _nsMatrix3.add(_eoTextField29);
            _eoTextField30.setSize(8, 13);
            _eoTextField30.setLocation(594, 0);
            _nsMatrix3.add(_eoTextField30);
            _eoTextField31.setSize(8, 13);
            _eoTextField31.setLocation(631, 0);
            _nsMatrix3.add(_eoTextField31);
            _eoTextField32.setSize(8, 13);
            _eoTextField32.setLocation(668, 0);
            _nsMatrix3.add(_eoTextField32);
            _eoTextField33.setSize(8, 13);
            _eoTextField33.setLocation(705, 0);
            _nsMatrix3.add(_eoTextField33);
            _eoTextField34.setSize(8, 13);
            _eoTextField34.setLocation(743, 0);
            _nsMatrix3.add(_eoTextField34);
            _eoTextField35.setSize(8, 13);
            _eoTextField35.setLocation(780, 0);
            _nsMatrix3.add(_eoTextField35);
            _eoTextField36.setSize(8, 13);
            _eoTextField36.setLocation(817, 0);
            _nsMatrix3.add(_eoTextField36);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_nsCustomView0, _nsMatrix3, "waterfallTicks");
        }

        _setFontForComponent(_nsTextField3, "Verdana", 9, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("-24");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_vUMeter0, _nsBox2, "background");
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_vUMeter0, _nsMatrix2, "matrix");
        }

        _setFontForComponent(_eoTextField13, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField12, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField11, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField10, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField9, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField8, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField7, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField6, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField5, "Lucida Grande", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _eoTextField5.setSize(6, 15);
            _eoTextField5.setLocation(0, 0);
            _nsMatrix2.add(_eoTextField5);
            _eoTextField6.setSize(6, 15);
            _eoTextField6.setLocation(7, 0);
            _nsMatrix2.add(_eoTextField6);
            _eoTextField7.setSize(6, 15);
            _eoTextField7.setLocation(14, 0);
            _nsMatrix2.add(_eoTextField7);
            _eoTextField8.setSize(6, 15);
            _eoTextField8.setLocation(21, 0);
            _nsMatrix2.add(_eoTextField8);
            _eoTextField9.setSize(6, 15);
            _eoTextField9.setLocation(28, 0);
            _nsMatrix2.add(_eoTextField9);
            _eoTextField10.setSize(6, 15);
            _eoTextField10.setLocation(35, 0);
            _nsMatrix2.add(_eoTextField10);
            _eoTextField11.setSize(6, 15);
            _eoTextField11.setLocation(42, 0);
            _nsMatrix2.add(_eoTextField11);
            _eoTextField12.setSize(6, 15);
            _eoTextField12.setLocation(49, 0);
            _nsMatrix2.add(_eoTextField12);
            _eoTextField13.setSize(6, 15);
            _eoTextField13.setLocation(56, 0);
            _nsMatrix2.add(_eoTextField13);
        }

        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsMatrix2.setSize(63, 15);
        _nsMatrix2.setLocation(1, 1);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsMatrix2, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsMatrix2);

        if (_replacedObjects.objectForKey("_nsBox2") == null) {
            if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
            _nsBox3.setSize(64, 17);
            _nsBox3.setLocation(1, 1);
            ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
            _nsBox2.add(_nsBox3);
            _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        }

        _setFontForComponent(_nsTextField2, "Verdana", 9, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("-12");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Verdana", 9, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("0dB");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _setFontForComponent(_nsSlider0, "Helvetica", 12, Font.PLAIN);
        }

        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsSlider0.setSize(86, 16);
        _nsSlider0.setLocation(807, 56);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsSlider0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsSlider0);
        _nsTextField1.setSize(29, 14);
        _nsTextField1.setLocation(876, 39);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsTextField2.setSize(30, 14);
        _nsTextField2.setLocation(836, 39);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField2);
        _nsBox2.setSize(66, 19);
        _nsBox2.setLocation(816, 16);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox2);
        _nsTextField3.setSize(30, 14);
        _nsTextField3.setLocation(798, 39);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField3);
        _nsCustomView0.setSize(778, 64);
        _nsCustomView0.setLocation(11, 5);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsCustomView0);
        _nsBox4.setSize(778, 15);
        _nsBox4.setLocation(11, 68);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox4);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(916, 88);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Verdana", 11, Font.PLAIN));

        if (_replacedObjects.objectForKey("_nsCustomView4") == null) {
            if (!(_nsCustomView4.getLayout() instanceof EOViewLayout)) { _nsCustomView4.setLayout(new EOViewLayout()); }
            _nsBox0.setSize(920, 92);
            _nsBox0.setLocation(23, 27);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsBox0);
            _nsBox6.setSize(177, 137);
            _nsBox6.setLocation(40, 171);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsBox6);
            _nsTextField8.setSize(55, 15);
            _nsTextField8.setLocation(32, 156);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField8);
            _nsBox10.setSize(908, 5);
            _nsBox10.setLocation(32, 340);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsBox10, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsBox10);
            _nsSlider3.setSize(115, 16);
            _nsSlider3.setLocation(360, 209);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsSlider3, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsSlider3);
            _nsTextField9.setSize(55, 15);
            _nsTextField9.setLocation(294, 211);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField9);
            _nsTextField10.setSize(30, 14);
            _nsTextField10.setLocation(349, 190);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField10);
            _nsTextField11.setSize(29, 14);
            _nsTextField11.setLocation(459, 190);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField11);
            _nsTextField12.setSize(30, 14);
            _nsTextField12.setLocation(402, 190);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField12);
            _nsButton3.setSize(64, 17);
            _nsButton3.setLocation(501, 210);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsButton3);
            _nsSlider4.setSize(115, 16);
            _nsSlider4.setLocation(728, 190);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsSlider4, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsSlider4);
            _nsTextField13.setSize(55, 15);
            _nsTextField13.setLocation(661, 192);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField13);
            _nsSlider5.setSize(115, 16);
            _nsSlider5.setLocation(728, 214);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsSlider5, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsSlider5);
            _nsTextField14.setSize(55, 15);
            _nsTextField14.setLocation(661, 216);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField14);
            _nsSlider6.setSize(115, 16);
            _nsSlider6.setLocation(728, 238);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsSlider6, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsSlider6);
            _nsTextField15.setSize(55, 15);
            _nsTextField15.setLocation(661, 240);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField15);
            _nsSlider7.setSize(115, 16);
            _nsSlider7.setLocation(728, 262);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsSlider7, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsSlider7);
            _nsTextField16.setSize(55, 15);
            _nsTextField16.setLocation(661, 264);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField16);
            _nsSlider8.setSize(115, 16);
            _nsSlider8.setLocation(728, 286);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsSlider8, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsSlider8);
            _nsTextField17.setSize(55, 15);
            _nsTextField17.setLocation(661, 288);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsTextField17);
            _nsButton4.setSize(125, 17);
            _nsButton4.setLocation(704, 158);
            ((EOViewLayout)_nsCustomView4.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
            _nsCustomView4.add(_nsButton4);
        }

        _setFontForComponent(_jButton1, "Lucida Grande", 10, Font.PLAIN);
        _jButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton0, "Lucida Grande", 10, Font.PLAIN);
        _jButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jButton0.setSize(59, 21);
            _jButton0.setLocation(0, 0);
            _nsMatrix1.add(_jButton0);
            _jButton1.setSize(59, 21);
            _jButton1.setLocation(0, 37);
            _nsMatrix1.add(_jButton1);
            _setFontForComponent(_nsMatrix1, "Lucida Grande", 10, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsMatrix1, "waveformMatrix");
        }

        _setFontForComponent(_eoTextField4, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Verdana", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _eoTextField0.setSize(37, 15);
            _eoTextField0.setLocation(0, 0);
            _nsMatrix0.add(_eoTextField0);
            _eoTextField1.setSize(37, 15);
            _eoTextField1.setLocation(92, 0);
            _nsMatrix0.add(_eoTextField1);
            _eoTextField2.setSize(37, 15);
            _eoTextField2.setLocation(184, 0);
            _nsMatrix0.add(_eoTextField2);
            _eoTextField3.setSize(37, 15);
            _eoTextField3.setLocation(276, 0);
            _nsMatrix0.add(_eoTextField3);
            _eoTextField4.setSize(37, 15);
            _eoTextField4.setLocation(368, 0);
            _nsMatrix0.add(_eoTextField4);
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsMatrix0, "specLabel");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsColorWell0, "plotColor");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField0.setEditable(true);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("0");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsTextField0, "inputPad");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsCustomView3, "soundInputControls");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsButton0, "activeButton");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_aMConfig0") == null) {
            _connect(_aMConfig0, _nsCustomView2, "soundFileControls");
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsCustomView2.setSize(150, 22);
        _nsCustomView2.setLocation(397, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView2);
        _nsCustomView3.setSize(520, 22);
        _nsCustomView3.setLocation(24, 64);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView3);
        _nsTextField18.setSize(39, 13);
        _nsTextField18.setLocation(43, 19);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField18);
        _nsButton0.setSize(58, 21);
        _nsButton0.setLocation(79, 15);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsBox12.setSize(176, 396);
        _nsBox12.setLocation(628, 56);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox12, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox12);
        _nsBox14.setSize(520, 16);
        _nsBox14.setLocation(15, 434);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox14, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox14);
        _nsCustomView1.setSize(520, 328);
        _nsCustomView1.setLocation(15, 109);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView1);
        _nsBox16.setSize(782, 5);
        _nsBox16.setLocation(17, 47);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox16, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox16);
        _nsMatrix1.setSize(59, 56);
        _nsMatrix1.setLocation(545, 161);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix1);
        _nsTextField0.setSize(24, 19);
        _nsTextField0.setLocation(566, 65);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField20.setSize(23, 19);
        _nsTextField20.setLocation(592, 67);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField20, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField20);
        _nsTextField21.setSize(23, 19);
        _nsTextField21.setLocation(542, 67);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField21, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField21);
        _nsButton1.setSize(58, 20);
        _nsButton1.setLocation(545, 291);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _popup0.setSize(53, 15);
        _popup0.setLocation(549, 256);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsTabView0.addTab("Receiver", _nsView0);
        _nsTabView0.addTab("Aural", _nsView1);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(824, 641);
        _nsTabView0.setLocation(-20, 0);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView2.setSize(787, 487);
            _eoFrame0.setTitle("Synchronous AM Configuration");
            _eoFrame0.setLocation(-1166, 515);
            _eoFrame0.setSize(787, 487);
        }
    }
}
