// _ModemEqualizer_EOArchive_English.java
// Generated by EnterpriseObjects palette at Thursday, November 30, 2006 7:30:57 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ModemEqualizer_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ModemEqualizerPlot _nsCustomView0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1, _nsMatrix2;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField10, _eoTextField11, _eoTextField12, _eoTextField13, _eoTextField14, _eoTextField15, _eoTextField16, _eoTextField17, _eoTextField18, _eoTextField19, _eoTextField2, _eoTextField20, _eoTextField21, _eoTextField22, _eoTextField23, _eoTextField24, _eoTextField25, _eoTextField3, _eoTextField4, _eoTextField5, _eoTextField6, _eoTextField7, _eoTextField8, _eoTextField9, _nsTextField0, _nsTextField1, _nsTextField2;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsCustomView1;
    javax.swing.JButton _nsButton0;

    public _ModemEqualizer_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoTextField25 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField24 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsMatrix2 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 4, 25, 8), "");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _eoTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(11, 1, 8, 16), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "plot")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ModemEqualizerPlot)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (ModemEqualizerPlot)_registered(new ModemEqualizerPlot(), "View");
        }

        _eoTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "power")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(11, 1, 8, 10), "");
        }

        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Close"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        _eoTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "plot");
        }

        _eoTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField1), ""));
        _eoTextField12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField12), ""));
        _eoTextField13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField13), ""));
        _eoTextField14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField14), ""));
        _eoTextField6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField6), ""));
        _eoTextField3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField3), ""));
        _eoTextField15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField15), ""));
        _eoTextField16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField16), ""));
        _eoTextField5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField5), ""));
        _eoTextField10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField10), ""));
        _eoTextField17.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "responseUpdated", _eoTextField17), ""));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "power");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "view");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "done", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_eoTextField25, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField24, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField23, "Verdana", 9, Font.PLAIN);
        _eoTextField23.setSize(43, 15);
        _eoTextField23.setLocation(0, 0);
        _nsMatrix2.add(_eoTextField23);
        _eoTextField9.setSize(43, 15);
        _eoTextField9.setLocation(68, 0);
        _nsMatrix2.add(_eoTextField9);
        _eoTextField24.setSize(43, 15);
        _eoTextField24.setLocation(136, 0);
        _nsMatrix2.add(_eoTextField24);
        _eoTextField25.setSize(43, 15);
        _eoTextField25.setLocation(204, 0);
        _nsMatrix2.add(_eoTextField25);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Applied Equalization");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(125, 1);
        _nsBox0.setLocation(2, 2);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox0);
        _nsBox1.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Frequency");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_eoTextField22, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField21, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField20, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField19, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField18, "Lucida Grande", 11, Font.PLAIN);
        _eoTextField18.setSize(58, 14);
        _eoTextField18.setLocation(0, 0);
        _nsMatrix1.add(_eoTextField18);
        _eoTextField19.setSize(58, 14);
        _eoTextField19.setLocation(0, 30);
        _nsMatrix1.add(_eoTextField19);
        _eoTextField7.setSize(58, 14);
        _eoTextField7.setLocation(0, 60);
        _nsMatrix1.add(_eoTextField7);
        _eoTextField2.setSize(58, 14);
        _eoTextField2.setLocation(0, 90);
        _nsMatrix1.add(_eoTextField2);
        _eoTextField8.setSize(58, 14);
        _eoTextField8.setLocation(0, 120);
        _nsMatrix1.add(_eoTextField8);
        _eoTextField20.setSize(58, 14);
        _eoTextField20.setLocation(0, 150);
        _nsMatrix1.add(_eoTextField20);
        _eoTextField0.setSize(58, 14);
        _eoTextField0.setLocation(0, 180);
        _nsMatrix1.add(_eoTextField0);
        _eoTextField21.setSize(58, 14);
        _eoTextField21.setLocation(0, 210);
        _nsMatrix1.add(_eoTextField21);
        _eoTextField11.setSize(58, 14);
        _eoTextField11.setLocation(0, 240);
        _nsMatrix1.add(_eoTextField11);
        _eoTextField4.setSize(58, 14);
        _eoTextField4.setLocation(0, 270);
        _nsMatrix1.add(_eoTextField4);
        _eoTextField22.setSize(58, 14);
        _eoTextField22.setLocation(0, 300);
        _nsMatrix1.add(_eoTextField22);
        _setFontForComponent(_eoTextField17, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField16, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField15, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField14, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField13, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField12, "Lucida Grande", 11, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _eoTextField1.setSize(57, 20);
            _eoTextField1.setLocation(0, 0);
            _nsMatrix0.add(_eoTextField1);
            _eoTextField12.setSize(57, 20);
            _eoTextField12.setLocation(0, 30);
            _nsMatrix0.add(_eoTextField12);
            _eoTextField13.setSize(57, 20);
            _eoTextField13.setLocation(0, 60);
            _nsMatrix0.add(_eoTextField13);
            _eoTextField14.setSize(57, 20);
            _eoTextField14.setLocation(0, 90);
            _nsMatrix0.add(_eoTextField14);
            _eoTextField6.setSize(57, 20);
            _eoTextField6.setLocation(0, 120);
            _nsMatrix0.add(_eoTextField6);
            _eoTextField3.setSize(57, 20);
            _eoTextField3.setLocation(0, 150);
            _nsMatrix0.add(_eoTextField3);
            _eoTextField15.setSize(57, 20);
            _eoTextField15.setLocation(0, 180);
            _nsMatrix0.add(_eoTextField15);
            _eoTextField16.setSize(57, 20);
            _eoTextField16.setLocation(0, 210);
            _nsMatrix0.add(_eoTextField16);
            _eoTextField5.setSize(57, 20);
            _eoTextField5.setLocation(0, 240);
            _nsMatrix0.add(_eoTextField5);
            _eoTextField10.setSize(57, 20);
            _eoTextField10.setLocation(0, 270);
            _nsMatrix0.add(_eoTextField10);
            _eoTextField17.setSize(57, 20);
            _eoTextField17.setLocation(0, 300);
            _nsMatrix0.add(_eoTextField17);
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
            _nsButton0.setSize(58, 21);
            _nsButton0.setLocation(525, 446);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsButton0);
            _nsMatrix1.setSize(59, 314);
            _nsMatrix1.setLocation(59, 81);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsMatrix1);
            _nsMatrix0.setSize(58, 320);
            _nsMatrix0.setLocation(156, 78);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsMatrix0);
            _nsTextField0.setSize(129, 14);
            _nsTextField0.setLocation(124, 44);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField0);
            _nsTextField1.setSize(82, 14);
            _nsTextField1.setLocation(43, 44);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField1);
            _nsCustomView0.setSize(288, 320);
            _nsCustomView0.setLocation(301, 78);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsCustomView0);
            _nsBox1.setSize(548, 5);
            _nsBox1.setLocation(54, 421);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsBox1);
            _nsTextField2.setSize(129, 14);
            _nsTextField2.setLocation(381, 35);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField2);
            _nsMatrix2.setSize(248, 15);
            _nsMatrix2.setLocation(308, 56);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsMatrix2, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsMatrix2);
        }

        _setFontForComponent(_eoTextField11, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField10, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField9, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField8, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField7, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField6, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField5, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Power (measured)");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        _setFontForComponent(_eoTextField4, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Lucida Grande", 11, Font.PLAIN);
    }
}
