// _SoftRock_EOArchive_English.java
// Generated by EnterpriseObjects palette at Friday, December 1, 2006 10:33:49 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _SoftRock_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    Oscilloscope _nsCustomView0;
    SoftRockConfig _softRockConfig0;
    VUMeter _vUMeter0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1, _nsMatrix2;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField10, _eoTextField11, _eoTextField12, _eoTextField13, _eoTextField2, _eoTextField3, _eoTextField4, _eoTextField5, _eoTextField6, _eoTextField7, _eoTextField8, _eoTextField9, _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsCustomView1, _nsCustomView2, _nsSlider0, _nsView0;
    javax.swing.JButton _jButton0, _jButton1, _nsButton0, _nsButton1;
    javax.swing.JCheckBox _nsButton2;
    javax.swing.JPanel _nsView1, _nsView2;
    javax.swing.JTabbedPane _nsTabView0;

    public _SoftRock_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111112");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "inputAttenuator")) != null)) {
            _nsSlider0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider0");
        } else {
            _nsSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider21");
        }

        _eoTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter.matrix")) != null)) {
            _nsMatrix2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix2");
        } else {
            _nsMatrix2 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 9, 1, 8), "");
        }

        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter.background")) != null)) {
            _nsBox6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsBox6");
        } else {
            _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "vuMeter")) != null)) {
            _vUMeter0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (VUMeter)replacement;
            _replacedObjects.setObjectForKey(replacement, "_vUMeter0");
        } else {
            _vUMeter0 = (VUMeter)_registered(new VUMeter(), "VUMeter");
        }

        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.inputPad")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        }

        _jButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Waveform"), "");
        _jButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Spectrum"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.waveformMatrix")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, -1, 16), "");
        }

        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView1");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1211");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.oscilloscope")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (Oscilloscope)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (Oscilloscope)_registered(new Oscilloscope(), "View12");
        }

        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.specLabel")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 5, 55, 8), "");
        }

        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsButton2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Fast Sound file playback."), "NSButton4");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.activeButton")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Inactive"), "");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.soundInputControls")) != null)) {
            _nsCustomView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView2");
        } else {
            _nsCustomView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.soundFileControls")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View2");
        }

        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config.window")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Config Panel");
        }

        _nsView2 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "config")) != null)) {
            _softRockConfig0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (SoftRockConfig)replacement;
            _replacedObjects.setObjectForKey(replacement, "_softRockConfig0");
        } else {
            _softRockConfig0 = (SoftRockConfig)_registered(new SoftRockConfig(), "SoftRockConfig");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "configButton")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Config"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        }

        _nsView1 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _connect(_owner(), _nsSlider0, "inputAttenuator");
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_owner(), _vUMeter0, "vuMeter");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _owner(), "modemObj");
        }

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_owner(), _softRockConfig0, "config");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "configButton");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField7, "Lucida Grande", 18, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("QRX...NOT YET...");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Verdana", 9, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("-24");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsTextField5, "Verdana", 9, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("-12");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Verdana", 9, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("0dB");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _setFontForComponent(_nsSlider0, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_vUMeter0, _nsMatrix2, "matrix");
        }

        _setFontForComponent(_eoTextField13, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField12, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField11, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField10, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField9, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField8, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField7, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField6, "Lucida Grande", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField5, "Lucida Grande", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix2") == null) {
            _eoTextField5.setSize(6, 15);
            _eoTextField5.setLocation(0, 0);
            _nsMatrix2.add(_eoTextField5);
            _eoTextField6.setSize(6, 15);
            _eoTextField6.setLocation(7, 0);
            _nsMatrix2.add(_eoTextField6);
            _eoTextField7.setSize(6, 15);
            _eoTextField7.setLocation(14, 0);
            _nsMatrix2.add(_eoTextField7);
            _eoTextField8.setSize(6, 15);
            _eoTextField8.setLocation(21, 0);
            _nsMatrix2.add(_eoTextField8);
            _eoTextField9.setSize(6, 15);
            _eoTextField9.setLocation(28, 0);
            _nsMatrix2.add(_eoTextField9);
            _eoTextField10.setSize(6, 15);
            _eoTextField10.setLocation(35, 0);
            _nsMatrix2.add(_eoTextField10);
            _eoTextField11.setSize(6, 15);
            _eoTextField11.setLocation(42, 0);
            _nsMatrix2.add(_eoTextField11);
            _eoTextField12.setSize(6, 15);
            _eoTextField12.setLocation(49, 0);
            _nsMatrix2.add(_eoTextField12);
            _eoTextField13.setSize(6, 15);
            _eoTextField13.setLocation(56, 0);
            _nsMatrix2.add(_eoTextField13);
        }

        if (!(_nsBox7.getLayout() instanceof EOViewLayout)) { _nsBox7.setLayout(new EOViewLayout()); }
        _nsMatrix2.setSize(63, 15);
        _nsMatrix2.setLocation(1, 1);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsMatrix2, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsMatrix2);

        if (_replacedObjects.objectForKey("_nsBox6") == null) {
            if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
            _nsBox7.setSize(64, 17);
            _nsBox7.setLocation(1, 1);
            ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
            _nsBox6.add(_nsBox7);
            _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        }

        if (_replacedObjects.objectForKey("_vUMeter0") == null) {
            _connect(_vUMeter0, _nsBox6, "background");
        }

        _setFontForComponent(_nsTextField3, "Verdana", 10, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Pad");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Verdana", 10, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("dB");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsTextField1, "inputPad");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("0");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsMatrix1, "waveformMatrix");
        }

        _setFontForComponent(_jButton1, "Lucida Grande", 10, Font.PLAIN);
        _jButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton0, "Lucida Grande", 10, Font.PLAIN);
        _jButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jButton0.setSize(59, 21);
            _jButton0.setLocation(0, 0);
            _nsMatrix1.add(_jButton0);
            _jButton1.setSize(59, 21);
            _jButton1.setLocation(0, 37);
            _nsMatrix1.add(_jButton1);
            _setFontForComponent(_nsMatrix1, "Lucida Grande", 10, Font.PLAIN);
        }

        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(125, 1);
        _nsBox5.setLocation(2, 2);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsCustomView0, "oscilloscope");
        }

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsMatrix0, "specLabel");
        }

        _setFontForComponent(_eoTextField4, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Verdana", 9, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Verdana", 9, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _eoTextField0.setSize(37, 15);
            _eoTextField0.setLocation(0, 0);
            _nsMatrix0.add(_eoTextField0);
            _eoTextField1.setSize(37, 15);
            _eoTextField1.setLocation(92, 0);
            _nsMatrix0.add(_eoTextField1);
            _eoTextField2.setSize(37, 15);
            _eoTextField2.setLocation(184, 0);
            _nsMatrix0.add(_eoTextField2);
            _eoTextField3.setSize(37, 15);
            _eoTextField3.setLocation(276, 0);
            _nsMatrix0.add(_eoTextField3);
            _eoTextField4.setSize(37, 15);
            _eoTextField4.setLocation(368, 0);
            _nsMatrix0.add(_eoTextField4);
        }

        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(406, 15);
        _nsMatrix0.setLocation(83, -1);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsMatrix0);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(518, 14);
        _nsBox3.setLocation(1, 1);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsButton2, "Lucida Grande", 10, Font.PLAIN);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsButton2.setSize(169, 17);
        _nsButton2.setLocation(18, 351);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton2);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(172, 392);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsButton1, "activeButton");
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("State:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsCustomView2, "soundInputControls");
        }

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _nsCustomView1, "soundFileControls");
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsCustomView1.setSize(150, 22);
        _nsCustomView1.setLocation(397, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView1);
        _nsCustomView2.setSize(520, 22);
        _nsCustomView2.setLocation(24, 64);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView2);
        _nsTextField0.setSize(39, 13);
        _nsTextField0.setLocation(43, 19);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton1.setSize(58, 21);
        _nsButton1.setLocation(79, 15);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsBox0.setSize(176, 396);
        _nsBox0.setLocation(628, 56);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsBox2.setSize(520, 16);
        _nsBox2.setLocation(15, 434);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox2);
        _nsCustomView0.setSize(520, 328);
        _nsCustomView0.setLocation(15, 109);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView0);
        _nsBox4.setSize(782, 5);
        _nsBox4.setLocation(17, 47);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox4);
        _nsMatrix1.setSize(59, 56);
        _nsMatrix1.setLocation(545, 161);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix1);
        _nsTextField1.setSize(24, 19);
        _nsTextField1.setLocation(566, 65);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField2.setSize(23, 19);
        _nsTextField2.setLocation(592, 67);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsTextField3.setSize(23, 19);
        _nsTextField3.setLocation(542, 67);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsTabView0.addTab("Receiver", _nsView0);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(824, 641);
        _nsTabView0.setLocation(-20, 0);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView2.setSize(787, 464);
            _eoFrame1.setTitle("SoftRock Configuration");
            _eoFrame1.setLocation(-1082, 164);
            _eoFrame1.setSize(787, 464);
        }

        if (_replacedObjects.objectForKey("_softRockConfig0") == null) {
            _connect(_softRockConfig0, _eoFrame1, "window");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(58, 21);
        _nsButton0.setLocation(620, 4);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton0);
        _nsBox6.setSize(66, 19);
        _nsBox6.setLocation(618, 38);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.MinYMargin);
        _nsView1.add(_nsBox6);
        _nsSlider0.setSize(86, 16);
        _nsSlider0.setLocation(610, 81);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsSlider0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsSlider0);
        _nsTextField4.setSize(29, 14);
        _nsTextField4.setLocation(679, 64);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField4);
        _nsTextField5.setSize(30, 14);
        _nsTextField5.setLocation(639, 64);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField5);
        _nsTextField6.setSize(30, 14);
        _nsTextField6.setLocation(601, 64);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField6);
        _nsTextField7.setSize(217, 39);
        _nsTextField7.setLocation(207, 38);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField7);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView1.setSize(711, 108);
            _eoFrame0.setTitle("SoftRock");
            _eoFrame0.setLocation(865, 322);
            _eoFrame0.setSize(711, 108);
        }
    }
}
