// _About_EOArchive_English.java
// Generated by EnterpriseObjects palette at Thursday, July 26, 2007 3:39:16 PM US/Pacific

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _About_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    AboutView _nsCustomView0, _nsCustomView1;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField10, _eoTextField11, _eoTextField12, _eoTextField13, _eoTextField14, _eoTextField2, _eoTextField3, _eoTextField4, _eoTextField5, _eoTextField6, _eoTextField7, _eoTextField8, _eoTextField9, _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1;
    javax.swing.JPanel _nsView0;

    public _About_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(15, 1, 8, 5), "");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1221");
        _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsCustomView1 = (AboutView)_registered(new AboutView(), "View");
        _nsCustomView0 = (AboutView)_registered(new AboutView(), "View");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "AboutPanel...");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_eoTextField14, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField13, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField12, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField11, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField10, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField9, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField8, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField7, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField6, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField5, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField4, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Verdana", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Verdana", 11, Font.PLAIN);
        _eoTextField0.setSize(184, 18);
        _eoTextField0.setLocation(0, 0);
        _nsMatrix0.add(_eoTextField0);
        _eoTextField1.setSize(184, 18);
        _eoTextField1.setLocation(0, 23);
        _nsMatrix0.add(_eoTextField1);
        _eoTextField2.setSize(184, 18);
        _eoTextField2.setLocation(0, 46);
        _nsMatrix0.add(_eoTextField2);
        _eoTextField3.setSize(184, 18);
        _eoTextField3.setLocation(0, 69);
        _nsMatrix0.add(_eoTextField3);
        _eoTextField4.setSize(184, 18);
        _eoTextField4.setLocation(0, 92);
        _nsMatrix0.add(_eoTextField4);
        _eoTextField5.setSize(184, 18);
        _eoTextField5.setLocation(0, 115);
        _nsMatrix0.add(_eoTextField5);
        _eoTextField6.setSize(184, 18);
        _eoTextField6.setLocation(0, 138);
        _nsMatrix0.add(_eoTextField6);
        _eoTextField7.setSize(184, 18);
        _eoTextField7.setLocation(0, 161);
        _nsMatrix0.add(_eoTextField7);
        _eoTextField8.setSize(184, 18);
        _eoTextField8.setLocation(0, 184);
        _nsMatrix0.add(_eoTextField8);
        _eoTextField9.setSize(184, 18);
        _eoTextField9.setLocation(0, 207);
        _nsMatrix0.add(_eoTextField9);
        _eoTextField10.setSize(184, 18);
        _eoTextField10.setLocation(0, 230);
        _nsMatrix0.add(_eoTextField10);
        _eoTextField11.setSize(184, 18);
        _eoTextField11.setLocation(0, 253);
        _nsMatrix0.add(_eoTextField11);
        _eoTextField12.setSize(184, 18);
        _eoTextField12.setLocation(0, 276);
        _nsMatrix0.add(_eoTextField12);
        _eoTextField13.setSize(184, 18);
        _eoTextField13.setLocation(0, 299);
        _nsMatrix0.add(_eoTextField13);
        _eoTextField14.setSize(184, 18);
        _eoTextField14.setLocation(0, 322);
        _nsMatrix0.add(_eoTextField14);
        _setFontForComponent(_nsTextField4, "Verdana", 16, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("cocoaModem 2.0");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Verdana", 11, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("w7ay@arrl.net");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Verdana", 10, Font.PLAIN + Font.ITALIC);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("with contributions and help from:");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _connect(_nsCustomView0, _nsTextField1, "versionString");
        _connect(_nsCustomView1, _nsTextField1, "versionString");
        _setFontForComponent(_nsTextField1, "Verdana", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Version 0.1");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField1.setSelectable(true);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(125, 1);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField0, "Verdana", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Kok Chen, W7AY");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(129, 17);
        _nsTextField0.setLocation(135, 114);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsTextField0);
        _nsBox0.setSize(206, 5);
        _nsBox0.setLocation(96, 177);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsBox0);
        _nsTextField1.setSize(91, 22);
        _nsTextField1.setLocation(161, 69);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsTextField1);
        _nsImageView0.setSize(64, 64);
        _nsImageView0.setLocation(80, 38);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsImageView0);
        _nsTextField2.setSize(189, 17);
        _nsTextField2.setLocation(105, 193);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsTextField2);
        _nsTextField3.setSize(129, 17);
        _nsTextField3.setLocation(135, 139);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsTextField3);
        _nsTextField4.setSize(154, 27);
        _nsTextField4.setLocation(148, 38);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsTextField4);
        _nsMatrix0.setSize(185, 340);
        _nsMatrix0.setLocation(104, 218);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsMatrix0);
        if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
        _nsCustomView1.setSize(386, 600);
        _nsCustomView1.setLocation(0, -11);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsCustomView1);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsCustomView0.setSize(386, 600);
        _nsCustomView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(365, 565);
            _eoFrame0.setTitle("");
            _eoFrame0.setLocation(1120, 171);
            _eoFrame0.setSize(365, 565);
        }
    }
}
